name = "tienda"
main = "src/index.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tienda-db"
database_id = "150a6872-880b-451d-a120-fd76d0d0bc39"
